#!/usr/bin/env ruby
# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.4)
require_relative 'SakaiScriptServiceDriver.rb'


module SakaiTest

endpoint_url = ARGV.shift
obj = SakaiScript.new(endpoint_url)

# run ruby with -d to see SOAP wiredumps.
obj.wiredump_dev = STDERR if $DEBUG

# SYNOPSIS
#   changeSiteShortDescription(sessionid, siteid, shortDescription)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   shortDescription C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = shortDescription = nil
puts obj.changeSiteShortDescription(sessionid, siteid, shortDescription)

# SYNOPSIS
#   changeSiteJoinable(sessionid, siteid, joinable, joinerrole, publicview)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   joinable        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#   joinerrole      C_String - {http://www.w3.org/2001/XMLSchema}string
#   publicview      Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = joinable = joinerrole = publicview = nil
puts obj.changeSiteJoinable(sessionid, siteid, joinable, joinerrole, publicview)

# SYNOPSIS
#   addMemberToAuthzGroupWithRole(sessionid, eid, authzgroupid, roleid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = authzgroupid = roleid = nil
puts obj.addMemberToAuthzGroupWithRole(sessionid, eid, authzgroupid, roleid)

# SYNOPSIS
#   copyRole(sessionid, authzgroupid1, authzgroupid2, roleid, description)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid1   C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid2   C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   description     C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid1 = authzgroupid2 = roleid = description = nil
puts obj.copyRole(sessionid, authzgroupid1, authzgroupid2, roleid, description)

# SYNOPSIS
#   changeSiteDescription(sessionid, siteid, description)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   description     C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = description = nil
puts obj.changeSiteDescription(sessionid, siteid, description)

# SYNOPSIS
#   getAllSitesForCurrentUser(sessionid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = nil
puts obj.getAllSitesForCurrentUser(sessionid)

# SYNOPSIS
#   addLTITool(sessionid, siteId, toolTitle, properties)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteId          C_String - {http://www.w3.org/2001/XMLSchema}string
#   toolTitle       C_String - {http://www.w3.org/2001/XMLSchema}string
#   properties      C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteId = toolTitle = properties = nil
puts obj.addLTITool(sessionid, siteId, toolTitle, properties)

# SYNOPSIS
#   addMemberToGroup(sessionid, siteid, groupid, userid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   groupid         C_String - {http://www.w3.org/2001/XMLSchema}string
#   userid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
sessionid = siteid = groupid = userid = nil
puts obj.addMemberToGroup(sessionid, siteid, groupid, userid)

# SYNOPSIS
#   addMemberToSiteWithRole(sessionid, siteid, eid, roleid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = eid = roleid = nil
puts obj.addMemberToSiteWithRole(sessionid, siteid, eid, roleid)

# SYNOPSIS
#   getSiteDefaultJoinerRole(sessionid, siteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = nil
puts obj.getSiteDefaultJoinerRole(sessionid, siteid)

# SYNOPSIS
#   checkForMemberInSite(sessionid, siteid, eid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
sessionid = siteid = eid = nil
puts obj.checkForMemberInSite(sessionid, siteid, eid)

# SYNOPSIS
#   checkForAuthzGroup(sessionid, authzgroupid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
sessionid = authzgroupid = nil
puts obj.checkForAuthzGroup(sessionid, authzgroupid)

# SYNOPSIS
#   removeMemberFromSiteBatch(sessionid, siteid, eid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = eid = nil
puts obj.removeMemberFromSiteBatch(sessionid, siteid, eid)

# SYNOPSIS
#   addNewToolToAllWorkspaces(sessionid, toolid, pagetitle, tooltitle, pagelayout, position, popup)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   toolid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   pagetitle       C_String - {http://www.w3.org/2001/XMLSchema}string
#   tooltitle       C_String - {http://www.w3.org/2001/XMLSchema}string
#   pagelayout      Int - {http://www.w3.org/2001/XMLSchema}int
#   position        Int - {http://www.w3.org/2001/XMLSchema}int
#   popup           Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = toolid = pagetitle = tooltitle = pagelayout = position = popup = nil
puts obj.addNewToolToAllWorkspaces(sessionid, toolid, pagetitle, tooltitle, pagelayout, position, popup)

# SYNOPSIS
#   changeSiteTitle(sessionid, siteid, title)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   title           C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = title = nil
puts obj.changeSiteTitle(sessionid, siteid, title)

# SYNOPSIS
#   addNewPageToSiteWithPosition(sessionid, siteid, pagetitle, pagelayout, position, popup)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   pagetitle       C_String - {http://www.w3.org/2001/XMLSchema}string
#   pagelayout      Int - {http://www.w3.org/2001/XMLSchema}int
#   position        Int - {http://www.w3.org/2001/XMLSchema}int
#   popup           Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = pagetitle = pagelayout = position = popup = nil
puts obj.addNewPageToSiteWithPosition(sessionid, siteid, pagetitle, pagelayout, position, popup)

# SYNOPSIS
#   checkForSite(sessionid, siteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
sessionid = siteid = nil
puts obj.checkForSite(sessionid, siteid)

# SYNOPSIS
#   getUserId(sessionid, eid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = nil
puts obj.getUserId(sessionid, eid)

# SYNOPSIS
#   getUserDisplayNameForCurrentUser(sessionid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = nil
puts obj.getUserDisplayNameForCurrentUser(sessionid)

# SYNOPSIS
#   getSessionForUser(sessionid, eid, wsonly)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   wsonly          Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = wsonly = nil
puts obj.getSessionForUser(sessionid, eid, wsonly)

# SYNOPSIS
#   changeUserEid(sessionid, eid, newEid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   newEid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = newEid = nil
puts obj.changeUserEid(sessionid, eid, newEid)

# SYNOPSIS
#   setSiteProperty(sessionid, siteid, propname, propvalue)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   propname        C_String - {http://www.w3.org/2001/XMLSchema}string
#   propvalue       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = propname = propvalue = nil
puts obj.setSiteProperty(sessionid, siteid, propname, propvalue)

# SYNOPSIS
#   setRoleForAuthzGroupMaintenance(sessionid, authzgroupid, roleid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = roleid = nil
puts obj.setRoleForAuthzGroupMaintenance(sessionid, authzgroupid, roleid)

# SYNOPSIS
#   changeUserType(sessionid, eid, type)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   type            C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = type = nil
puts obj.changeUserType(sessionid, eid, type)

# SYNOPSIS
#   getAllSitesForUser(sessionid, eid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = nil
puts obj.getAllSitesForUser(sessionid, eid)

# SYNOPSIS
#   getGroupsInSite(sessionid, siteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = nil
puts obj.getGroupsInSite(sessionid, siteid)

# SYNOPSIS
#   getPagesAndToolsForSite(sessionid, eid, siteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = siteid = nil
puts obj.getPagesAndToolsForSite(sessionid, eid, siteid)

# SYNOPSIS
#   removeUser(sessionid, eid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = nil
puts obj.removeUser(sessionid, eid)

# SYNOPSIS
#   removeAllRolesFromAuthzGroup(sessionid, authzgroupid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = nil
puts obj.removeAllRolesFromAuthzGroup(sessionid, authzgroupid)

# SYNOPSIS
#   addNewToolToPage(sessionid, siteid, pagetitle, tooltitle, toolid, layouthints)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   pagetitle       C_String - {http://www.w3.org/2001/XMLSchema}string
#   tooltitle       C_String - {http://www.w3.org/2001/XMLSchema}string
#   toolid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   layouthints     C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = pagetitle = tooltitle = toolid = layouthints = nil
puts obj.addNewToolToPage(sessionid, siteid, pagetitle, tooltitle, toolid, layouthints)

# SYNOPSIS
#   addNewUser(sessionid, eid, firstname, lastname, email, type, password)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   firstname       C_String - {http://www.w3.org/2001/XMLSchema}string
#   lastname        C_String - {http://www.w3.org/2001/XMLSchema}string
#   email           C_String - {http://www.w3.org/2001/XMLSchema}string
#   type            C_String - {http://www.w3.org/2001/XMLSchema}string
#   password        C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = firstname = lastname = email = type = password = nil
puts obj.addNewUser(sessionid, eid, firstname, lastname, email, type, password)

# SYNOPSIS
#   disallowAllFunctionsForRole(sessionid, authzgroupid, roleid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = roleid = nil
puts obj.disallowAllFunctionsForRole(sessionid, authzgroupid, roleid)

# SYNOPSIS
#   getAvailableRoles(sessionid, authzgroupid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = nil
puts obj.getAvailableRoles(sessionid, authzgroupid)

# SYNOPSIS
#   getSubSites(sessionid, siteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = nil
puts obj.getSubSites(sessionid, siteid)

# SYNOPSIS
#   searchForUsers(sessionid, criteria, first, last)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   criteria        C_String - {http://www.w3.org/2001/XMLSchema}string
#   first           Int - {http://www.w3.org/2001/XMLSchema}int
#   last            Int - {http://www.w3.org/2001/XMLSchema}int
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = criteria = first = last = nil
puts obj.searchForUsers(sessionid, criteria, first, last)

# SYNOPSIS
#   checkForMemberInAuthzGroupWithRole(sessionid, eid, authzgroupid, role)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   role            C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
sessionid = eid = authzgroupid = role = nil
puts obj.checkForMemberInAuthzGroupWithRole(sessionid, eid, authzgroupid, role)

# SYNOPSIS
#   getSiteDescription(sessionid, siteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = nil
puts obj.getSiteDescription(sessionid, siteid)

# SYNOPSIS
#   getUsersInAuthzGroup(sessionid, authzgroupid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = nil
puts obj.getUsersInAuthzGroup(sessionid, authzgroupid)

# SYNOPSIS
#   setUserProperty(sessionid, eid, key, value)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   key             C_String - {http://www.w3.org/2001/XMLSchema}string
#   value           C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = key = value = nil
puts obj.setUserProperty(sessionid, eid, key, value)

# SYNOPSIS
#   copyRole2(sessionid, authzgroupid1, authzgroupid2, roleid, description, removeBeforeSync)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid1   C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid2   C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   description     C_String - {http://www.w3.org/2001/XMLSchema}string
#   removeBeforeSync Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid1 = authzgroupid2 = roleid = description = removeBeforeSync = nil
puts obj.copyRole2(sessionid, authzgroupid1, authzgroupid2, roleid, description, removeBeforeSync)

# SYNOPSIS
#   changeSiteSkin(sessionid, siteid, skin)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   skin            C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = skin = nil
puts obj.changeSiteSkin(sessionid, siteid, skin)

# SYNOPSIS
#   addCalendarEvent(sessionid, sourceSiteId, startTime, endTime, startIncluded, endIncluded, displayName, description, type, location, descriptionFormatted, recurrenceFrequency, recurrenceInterval)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   sourceSiteId    C_String - {http://www.w3.org/2001/XMLSchema}string
#   startTime       Long - {http://www.w3.org/2001/XMLSchema}long
#   endTime         Long - {http://www.w3.org/2001/XMLSchema}long
#   startIncluded   Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#   endIncluded     Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#   displayName     C_String - {http://www.w3.org/2001/XMLSchema}string
#   description     C_String - {http://www.w3.org/2001/XMLSchema}string
#   type            C_String - {http://www.w3.org/2001/XMLSchema}string
#   location        C_String - {http://www.w3.org/2001/XMLSchema}string
#   descriptionFormatted C_String - {http://www.w3.org/2001/XMLSchema}string
#   recurrenceFrequency C_String - {http://www.w3.org/2001/XMLSchema}string
#   recurrenceInterval Int - {http://www.w3.org/2001/XMLSchema}int
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = sourceSiteId = startTime = endTime = startIncluded = endIncluded = displayName = description = type = location = descriptionFormatted = recurrenceFrequency = recurrenceInterval = nil
puts obj.addCalendarEvent(sessionid, sourceSiteId, startTime, endTime, startIncluded, endIncluded, displayName, description, type, location, descriptionFormatted, recurrenceFrequency, recurrenceInterval)

# SYNOPSIS
#   addNewUserWithInternalId(sessionid, id, eid, firstname, lastname, email, type, password)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   id              C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   firstname       C_String - {http://www.w3.org/2001/XMLSchema}string
#   lastname        C_String - {http://www.w3.org/2001/XMLSchema}string
#   email           C_String - {http://www.w3.org/2001/XMLSchema}string
#   type            C_String - {http://www.w3.org/2001/XMLSchema}string
#   password        C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = id = eid = firstname = lastname = email = type = password = nil
puts obj.addNewUserWithInternalId(sessionid, id, eid, firstname, lastname, email, type, password)

# SYNOPSIS
#   addMemberToSiteWithRoleBatch(sessionid, siteid, eids, roleid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   eids            C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = eids = roleid = nil
puts obj.addMemberToSiteWithRoleBatch(sessionid, siteid, eids, roleid)

# SYNOPSIS
#   checkForUserById(sessionid, userid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   userid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
sessionid = userid = nil
puts obj.checkForUserById(sessionid, userid)

# SYNOPSIS
#   getUsersInAuthzGroupWithRole(sessionid, authzgroupid, authzgrouproles)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgrouproles C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = authzgrouproles = nil
puts obj.getUsersInAuthzGroupWithRole(sessionid, authzgroupid, authzgrouproles)

# SYNOPSIS
#   changeUserPassword(sessionid, eid, password)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   password        C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = password = nil
puts obj.changeUserPassword(sessionid, eid, password)

# SYNOPSIS
#   setUserTimeZone(sessionid, eid, timeZoneId)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   timeZoneId      C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = timeZoneId = nil
puts obj.setUserTimeZone(sessionid, eid, timeZoneId)

# SYNOPSIS
#   copySiteContent(sessionid, sourcesiteid, destinationsiteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   sourcesiteid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   destinationsiteid C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = sourcesiteid = destinationsiteid = nil
puts obj.copySiteContent(sessionid, sourcesiteid, destinationsiteid)

# SYNOPSIS
#   getAllUsers(sessionid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = nil
puts obj.getAllUsers(sessionid)

# SYNOPSIS
#   addConfigPropertyToPage(sessionid, siteid, pagetitle, propname, propvalue)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   pagetitle       C_String - {http://www.w3.org/2001/XMLSchema}string
#   propname        C_String - {http://www.w3.org/2001/XMLSchema}string
#   propvalue       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = pagetitle = propname = propvalue = nil
puts obj.addConfigPropertyToPage(sessionid, siteid, pagetitle, propname, propvalue)

# SYNOPSIS
#   getSessionTotalCount(sessionid, millisBeforeExpire)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   millisBeforeExpire Int - {http://www.w3.org/2001/XMLSchema}int
#
# RETURNS
#   v_return        Int - {http://www.w3.org/2001/XMLSchema}int
#
sessionid = millisBeforeExpire = nil
puts obj.getSessionTotalCount(sessionid, millisBeforeExpire)

# SYNOPSIS
#   addConfigPropertyToTool(sessionid, siteid, pagetitle, tooltitle, propname, propvalue)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   pagetitle       C_String - {http://www.w3.org/2001/XMLSchema}string
#   tooltitle       C_String - {http://www.w3.org/2001/XMLSchema}string
#   propname        C_String - {http://www.w3.org/2001/XMLSchema}string
#   propvalue       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = pagetitle = tooltitle = propname = propvalue = nil
puts obj.addConfigPropertyToTool(sessionid, siteid, pagetitle, tooltitle, propname, propvalue)

# SYNOPSIS
#   getUserIdForCurrentUser(sessionid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = nil
puts obj.getUserIdForCurrentUser(sessionid)

# SYNOPSIS
#   changeSiteIconUrl(sessionid, siteid, iconurl)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   iconurl         C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = iconurl = nil
puts obj.changeSiteIconUrl(sessionid, siteid, iconurl)

# SYNOPSIS
#   checkForEmptyRolesInAuthzGroup(sessionid, authzgroupid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
sessionid = authzgroupid = nil
puts obj.checkForEmptyRolesInAuthzGroup(sessionid, authzgroupid)

# SYNOPSIS
#   addNewAuthzGroup(sessionid, authzgroupid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = nil
puts obj.addNewAuthzGroup(sessionid, authzgroupid)

# SYNOPSIS
#   allowFunctionForRole(sessionid, authzgroupid, roleid, functionname)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   functionname    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = roleid = functionname = nil
puts obj.allowFunctionForRole(sessionid, authzgroupid, roleid, functionname)

# SYNOPSIS
#   getPlacementId(sessionid, siteId, toolId)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteId          C_String - {http://www.w3.org/2001/XMLSchema}string
#   toolId          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteId = toolId = nil
puts obj.getPlacementId(sessionid, siteId, toolId)

# SYNOPSIS
#   changeUserName(sessionid, eid, firstname, lastname)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   firstname       C_String - {http://www.w3.org/2001/XMLSchema}string
#   lastname        C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = firstname = lastname = nil
puts obj.changeUserName(sessionid, eid, firstname, lastname)

# SYNOPSIS
#   getUserEmailForCurrentUser(sessionid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = nil
puts obj.getUserEmailForCurrentUser(sessionid)

# SYNOPSIS
#   removeRoleFromAuthzGroup(sessionid, authzgroupid, roleid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = roleid = nil
puts obj.removeRoleFromAuthzGroup(sessionid, authzgroupid, roleid)

# SYNOPSIS
#   checkSession(sessionid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = nil
puts obj.checkSession(sessionid)

# SYNOPSIS
#   getSitesUserCanAccess(sessionid, eid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = nil
puts obj.getSitesUserCanAccess(sessionid, eid)

# SYNOPSIS
#   findSitesByPropertyValue(sessionid, propertyName, propertyValue)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   propertyName    C_String - {http://www.w3.org/2001/XMLSchema}string
#   propertyValue   C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = propertyName = propertyValue = nil
puts obj.findSitesByPropertyValue(sessionid, propertyName, propertyValue)

# SYNOPSIS
#   removeAuthzGroup(sessionid, authzgroupid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = nil
puts obj.removeAuthzGroup(sessionid, authzgroupid)

# SYNOPSIS
#   changeUserLocale(sessionid, eid, locale)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   locale          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = locale = nil
puts obj.changeUserLocale(sessionid, eid, locale)

# SYNOPSIS
#   getUserDisplayName(sessionid, eid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = nil
puts obj.getUserDisplayName(sessionid, eid)

# SYNOPSIS
#   getSessionCountForServer(sessionid, serverid, millisBeforeExpire)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   serverid        C_String - {http://www.w3.org/2001/XMLSchema}string
#   millisBeforeExpire Int - {http://www.w3.org/2001/XMLSchema}int
#
# RETURNS
#   v_return        Int - {http://www.w3.org/2001/XMLSchema}int
#
sessionid = serverid = millisBeforeExpire = nil
puts obj.getSessionCountForServer(sessionid, serverid, millisBeforeExpire)

# SYNOPSIS
#   getSiteSkin(sessionid, siteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = nil
puts obj.getSiteSkin(sessionid, siteid)

# SYNOPSIS
#   getUserProperty(sessionid, eid, propertyName)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   propertyName    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = propertyName = nil
puts obj.getUserProperty(sessionid, eid, propertyName)

# SYNOPSIS
#   copySiteContentForTool(sessionid, sourcesiteid, destinationsiteid, toolid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   sourcesiteid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   destinationsiteid C_String - {http://www.w3.org/2001/XMLSchema}string
#   toolid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = sourcesiteid = destinationsiteid = toolid = nil
puts obj.copySiteContentForTool(sessionid, sourcesiteid, destinationsiteid, toolid)

# SYNOPSIS
#   getExistingFunctions(sessionid, authzgroupid, roleid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = roleid = nil
puts obj.getExistingFunctions(sessionid, authzgroupid, roleid)

# SYNOPSIS
#   getSiteProperty(sessionid, siteid, propname)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   propname        C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = propname = nil
puts obj.getSiteProperty(sessionid, siteid, propname)

# SYNOPSIS
#   addGroupToSite(sessionid, siteid, grouptitle, groupdesc)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   grouptitle      C_String - {http://www.w3.org/2001/XMLSchema}string
#   groupdesc       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = grouptitle = groupdesc = nil
puts obj.addGroupToSite(sessionid, siteid, grouptitle, groupdesc)

# SYNOPSIS
#   copyCalendarEvents(sessionid, sourceSiteId, targetSiteId)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   sourceSiteId    C_String - {http://www.w3.org/2001/XMLSchema}string
#   targetSiteId    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = sourceSiteId = targetSiteId = nil
puts obj.copyCalendarEvents(sessionid, sourceSiteId, targetSiteId)

# SYNOPSIS
#   addToolAndPageToSite(sessionid, siteid, toolid, pagetitle, tooltitle, pagelayout, position, popup)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   toolid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   pagetitle       C_String - {http://www.w3.org/2001/XMLSchema}string
#   tooltitle       C_String - {http://www.w3.org/2001/XMLSchema}string
#   pagelayout      Int - {http://www.w3.org/2001/XMLSchema}int
#   position        Int - {http://www.w3.org/2001/XMLSchema}int
#   popup           Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = toolid = pagetitle = tooltitle = pagelayout = position = popup = nil
puts obj.addToolAndPageToSite(sessionid, siteid, toolid, pagetitle, tooltitle, pagelayout, position, popup)

# SYNOPSIS
#   getPagesAndToolsForSiteForCurrentUser(sessionid, siteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = nil
puts obj.getPagesAndToolsForSiteForCurrentUser(sessionid, siteid)

# SYNOPSIS
#   setRoleDescription(sessionid, authzgroupid, roleid, description)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   description     C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = roleid = description = nil
puts obj.setRoleDescription(sessionid, authzgroupid, roleid, description)

# SYNOPSIS
#   addNewRoleToAuthzGroup(sessionid, authzgroupid, roleid, description)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   description     C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = roleid = description = nil
puts obj.addNewRoleToAuthzGroup(sessionid, authzgroupid, roleid, description)

# SYNOPSIS
#   findSitesByTitle(sessionid, criteria)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   criteria        C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = criteria = nil
puts obj.findSitesByTitle(sessionid, criteria)

# SYNOPSIS
#   checkForUser(sessionid, eid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
sessionid = eid = nil
puts obj.checkForUser(sessionid, eid)

# SYNOPSIS
#   changeUserInfo(sessionid, eid, firstname, lastname, email, type, password)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   firstname       C_String - {http://www.w3.org/2001/XMLSchema}string
#   lastname        C_String - {http://www.w3.org/2001/XMLSchema}string
#   email           C_String - {http://www.w3.org/2001/XMLSchema}string
#   type            C_String - {http://www.w3.org/2001/XMLSchema}string
#   password        C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = firstname = lastname = email = type = password = nil
puts obj.changeUserInfo(sessionid, eid, firstname, lastname, email, type, password)

# SYNOPSIS
#   isSiteJoinable(sessionid, siteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
sessionid = siteid = nil
puts obj.isSiteJoinable(sessionid, siteid)

# SYNOPSIS
#   removeMemberFromSite(sessionid, siteid, eid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = eid = nil
puts obj.removeMemberFromSite(sessionid, siteid, eid)

# SYNOPSIS
#   getUserEmail(sessionid, eid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = nil
puts obj.getUserEmail(sessionid, eid)

# SYNOPSIS
#   getUserType(sessionid, eid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = nil
puts obj.getUserType(sessionid, eid)

# SYNOPSIS
#   removePageFromSite(sessionid, siteid, pagetitle)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   pagetitle       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = pagetitle = nil
puts obj.removePageFromSite(sessionid, siteid, pagetitle)

# SYNOPSIS
#   changeUserEmail(sessionid, eid, email)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   email           C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = email = nil
puts obj.changeUserEmail(sessionid, eid, email)

# SYNOPSIS
#   disallowFunctionForRole(sessionid, authzgroupid, roleid, functionname)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   functionname    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = roleid = functionname = nil
puts obj.disallowFunctionForRole(sessionid, authzgroupid, roleid, functionname)

# SYNOPSIS
#   removeSite(sessionid, siteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = nil
puts obj.removeSite(sessionid, siteid)

# SYNOPSIS
#   findSitesByProperty(sessionid, propertyName)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   propertyName    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = propertyName = nil
puts obj.findSitesByProperty(sessionid, propertyName)

# SYNOPSIS
#   removeAllMembersFromAuthzGroup(sessionid, authzgroupid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = authzgroupid = nil
puts obj.removeAllMembersFromAuthzGroup(sessionid, authzgroupid)

# SYNOPSIS
#   addNewSite(sessionid, siteid, title, description, shortdesc, iconurl, infourl, joinable, joinerrole, published, publicview, skin, type)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   title           C_String - {http://www.w3.org/2001/XMLSchema}string
#   description     C_String - {http://www.w3.org/2001/XMLSchema}string
#   shortdesc       C_String - {http://www.w3.org/2001/XMLSchema}string
#   iconurl         C_String - {http://www.w3.org/2001/XMLSchema}string
#   infourl         C_String - {http://www.w3.org/2001/XMLSchema}string
#   joinable        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#   joinerrole      C_String - {http://www.w3.org/2001/XMLSchema}string
#   published       Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#   publicview      Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#   skin            C_String - {http://www.w3.org/2001/XMLSchema}string
#   type            C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = title = description = shortdesc = iconurl = infourl = joinable = joinerrole = published = publicview = skin = type = nil
puts obj.addNewSite(sessionid, siteid, title, description, shortdesc, iconurl, infourl, joinable, joinerrole, published, publicview, skin, type)

# SYNOPSIS
#   getSiteTitle(sessionid, siteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = nil
puts obj.getSiteTitle(sessionid, siteid)

# SYNOPSIS
#   removeSiteProperty(sessionid, siteid, propname)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   propname        C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = propname = nil
puts obj.removeSiteProperty(sessionid, siteid, propname)

# SYNOPSIS
#   changeSitePublishStatus(sessionid, siteid, published)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   published       Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = published = nil
puts obj.changeSitePublishStatus(sessionid, siteid, published)

# SYNOPSIS
#   copyResources(sessionid, sourcesiteid, destinationsiteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   sourcesiteid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   destinationsiteid C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = sourcesiteid = destinationsiteid = nil
puts obj.copyResources(sessionid, sourcesiteid, destinationsiteid)

# SYNOPSIS
#   removeMemberFromAuthzGroup(sessionid, eid, authzgroupid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = authzgroupid = nil
puts obj.removeMemberFromAuthzGroup(sessionid, eid, authzgroupid)

# SYNOPSIS
#   checkForRoleInAuthzGroup(sessionid, authzgroupid, roleid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   roleid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
sessionid = authzgroupid = roleid = nil
puts obj.checkForRoleInAuthzGroup(sessionid, authzgroupid, roleid)

# SYNOPSIS
#   getSessionForCurrentUser(sessionid, eid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = eid = nil
puts obj.getSessionForCurrentUser(sessionid, eid)

# SYNOPSIS
#   copySite(sessionid, siteidtocopy, newsiteid, title, description, shortdesc, iconurl, infourl, joinable, joinerrole, published, publicview, skin, type)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteidtocopy    C_String - {http://www.w3.org/2001/XMLSchema}string
#   newsiteid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   title           C_String - {http://www.w3.org/2001/XMLSchema}string
#   description     C_String - {http://www.w3.org/2001/XMLSchema}string
#   shortdesc       C_String - {http://www.w3.org/2001/XMLSchema}string
#   iconurl         C_String - {http://www.w3.org/2001/XMLSchema}string
#   infourl         C_String - {http://www.w3.org/2001/XMLSchema}string
#   joinable        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#   joinerrole      C_String - {http://www.w3.org/2001/XMLSchema}string
#   published       Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#   publicview      Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#   skin            C_String - {http://www.w3.org/2001/XMLSchema}string
#   type            C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteidtocopy = newsiteid = title = description = shortdesc = iconurl = infourl = joinable = joinerrole = published = publicview = skin = type = nil
puts obj.copySite(sessionid, siteidtocopy, newsiteid, title, description, shortdesc, iconurl, infourl, joinable, joinerrole, published, publicview, skin, type)

# SYNOPSIS
#   isSuperUser(sessionid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
sessionid = nil
puts obj.isSuperUser(sessionid)

# SYNOPSIS
#   checkForUserInAuthzGroup(sessionid, authzgroupid, eid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   authzgroupid    C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
sessionid = authzgroupid = eid = nil
puts obj.checkForUserInAuthzGroup(sessionid, authzgroupid, eid)

# SYNOPSIS
#   changeSiteMemberStatus(sessionid, siteid, eid, active)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   eid             C_String - {http://www.w3.org/2001/XMLSchema}string
#   active          Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = eid = active = nil
puts obj.changeSiteMemberStatus(sessionid, siteid, eid, active)

# SYNOPSIS
#   resetAllUserWorkspace(sessionid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        Boolean - {http://www.w3.org/2001/XMLSchema}boolean
#
sessionid = nil
puts obj.resetAllUserWorkspace(sessionid)

# SYNOPSIS
#   getParentSite(sessionid, siteid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = nil
puts obj.getParentSite(sessionid, siteid)

# SYNOPSIS
#   getSitesCurrentUserCanAccess(sessionid)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = nil
puts obj.getSitesCurrentUserCanAccess(sessionid)

# SYNOPSIS
#   addNewPageToSite(sessionid, siteid, pagetitle, pagelayout)
#
# ARGS
#   sessionid       C_String - {http://www.w3.org/2001/XMLSchema}string
#   siteid          C_String - {http://www.w3.org/2001/XMLSchema}string
#   pagetitle       C_String - {http://www.w3.org/2001/XMLSchema}string
#   pagelayout      Int - {http://www.w3.org/2001/XMLSchema}int
#
# RETURNS
#   v_return        C_String - {http://www.w3.org/2001/XMLSchema}string
#
sessionid = siteid = pagetitle = pagelayout = nil
puts obj.addNewPageToSite(sessionid, siteid, pagetitle, pagelayout)




end
